//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Resource
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string FileName { get; set; }
    public byte[] Content { get; set; }
}

public partial class UserProfile
{
    public UserProfile()
    {
        this.EmailUpdates = false;
        this.ExclusiveContent = false;
    }

    public int Id { get; set; }
    public string Email { get; set; }
    public string FName { get; set; }
    public string LName { get; set; }
    public string ProfessionalDesignation { get; set; }
    public string Specialty { get; set; }
    public string OtherSpecialty { get; set; }
    public bool EmailUpdates { get; set; }
    public Nullable<bool> ExclusiveContent { get; set; }
    public string HCPVerificationMethod { get; set; }
    public string StateLicenseNumber { get; set; }
    public string StateOfLicensure { get; set; }
    public string NPINumber { get; set; }
    public string BusinessAddressLine1 { get; set; }
    public string BusinessAddressLine2 { get; set; }
    public string BusinessAddressCity { get; set; }
    public string BusinessAddressState { get; set; }
    public string BusinessAddressZip { get; set; }
    public string TreatmentQuestionResponse { get; set; }
}
